name: Top Soccer Drills For Better Coaching
favicon: null
layout_spectrum: 0.5271282005123794
typography_spectrum: 0.17967213760130107
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.019019583240151405
  lightness: 0.464616974350065
  saturation: 0.912782774772495
  rhythmicContrast: 0.3723954048473388
purpose: []
