name: Top Soccer Drills For Better Coaching
favicon: null
layout_spectrum: 0.5271282005123794
typography_spectrum: 0.17967213760130107
title: Top Soccer Drills For Better Coaching
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e0ffb3'
    - '#808080'
    - '#000000'
    - '#00ff00'
    - '#aaff00'
  brandStrength: 0.5
  lightness: 0.464616974350065
  saturation: 0.912782774772495
  rhythmicContrast: 0.3723954048473388
purpose: []
